### ISSUE TITLE
Error with :init in 0.9.0

### ISSUE THREAD

**Issue by arohner** [weavejester/lein-ring#143]
In project.clj:

```clojure
:ring {:init foo.main/-main
       :handler foo.system/ring-handler}
```
`lein ring war` works fine with this on 0.8.13, but fails on 0.9.0 with

`Exception in thread "main" java.lang.Exception: Found lib name 'foo.system' containing period with prefix 'foo.main'.  lib names inside prefix lists must not contain periods`

Commenting out :init makes the war compile on 0.9.0

**Comment by MichaelBlume** [comment]
Thanks for the report, digging now

**Comment by MichaelBlume** [comment]
Fixed in master, thanks again for the report.

@weavejester can I just push a commit with 0.9.1 in the project.clj and get a new release or is there more that needs to be done?

**Comment by weavejester** [comment]
I'll push out a new release tomorrow. In future, could you also make sure that your commit messages have the same format as the other commits in the repository?
