### ISSUE TITLE
Option to include test classpath as well as main classpath

### ISSUE THREAD

**Issue by hlship** [weavejester/lein-ring#16]
Occasionally, it is useful to include the test classpath when executing "lein ring server".  In my particular case, I'm developing a web toolkit and want to be able to run a test application built in the toolkit. Ideally, the namespaces defining the test application would be in my test folder, but currently I'm forced to put them in my src folder (which also means they'll be distributed in my jar file).

Maybe "lein ring test-server" ... or an option inside project.clj.

**Comment by MichaelBlume** [comment]
Hm, interesting. I usually work around this by just developing in a REPL session and running my app through run-jetty, but I think this makes sense too. I think a project.clj option or a command line option makes more sense than a brand new command. tests-in-server? tests-in-dev? not sure.

**Comment by mwmitchell** [comment]
I just add my "test" dir to the `:dev` environment `:src` path. Works great. If that doesn't work, seems like Leiningen profiles would work fine: `lein with-profile +my-test-profile ring server`

**Comment by MichaelBlume** [comment]
Yeah, that makes sense. Closing because this seems like something that doesn't really need a lein-ring specific solution. Feel free to reopen
