### ISSUE TITLE
How does lein-ring know if it is in development or production?

### ISSUE THREAD

**Issue by gja** [weavejester/lein-ring#160]
Please add answer to the README.md

Referenced here:

* :stacktraces? - If true, display a stacktrace when an exception is thrown. Defaults to true in development mode, false in production.
* :auto-reload? - If true, automatically reload modified source files. Defaults to true in development mode, false in production.

**Comment by weavejester** [comment]
The README does mention the `LEIN_NO_DEV` variable, but it could be clearer.
