### ISSUE TITLE
Creating uberwars with ring-1.6.0 async support

### ISSUE THREAD

**Issue by sander** [weavejester/lein-ring#176]
I’m trying to deploy an app to my jetty9 server using the async support in ring-1.6.0-beta5. While the app works fine with `lein ring server-headless`, the version created with `lein ring uberwar` doesn’t seem to work:

```
clojure.lang.ArityException: Wrong number of args (1) passed to: core/handler
```

My code and the stack trace are at https://gist.github.com/sander/73b37a2684dfdbb0c3d1106c10525253. I am using:
- OS X 10.11.6 (15G31)
- JRE 1.8.0_101-b13
- Jetty 9.3.11.v20160721
- lein-ring 0.9.7
- ring 1.6.0-beta5

The error seems to be expected, since README.md tells that the `:adapter` option has no effect when deploying the app as a war file. I use `:adapter {:async? true}` to make the embedded server run the handler asynchronously.

Is there another way to create a war file that will be handled asynchronously by jetty9?

**Comment by weavejester** [comment]
Lein-Ring doesn't currently support this, I'm afraid. The `make-service-method` function in Ring supports generating asynchronous servlets, but it needs an `:async?` option that Lein-Ring doesn't currently pass to it. I'd welcome any PRs that would add this functionality.
