### ISSUE TITLE
Restarting server-headless via nREPL

### ISSUE THREAD

**Issue by dkharlan** [weavejester/lein-ring#178]
Is there a way to swap out the active handler via the REPL?

Something like this...

```
(defn something [request]
  ...)

(def app
  (routes
    (GET "/something" request (something request))))
```

...followed by a change to `something` and then C-c C-k.

Is there a way to automatically refresh, or to manually swap the handler?

I'm writing an integration with a third party service that requires a stable domain name, so I'm port-forwarding an nREPL to develop on a remote machine.  Thus no files actually change, and nothing refreshes.  This is running in Docker so I'd like to avoid restarting the lein ring task (and thus the container).

**Comment by dkharlan** [comment]
Nevermind... typo was tripping me up.

**Comment by MichaelBlume** [comment]
Cool, you've got your use case fully taken care of?

**Comment by dkharlan** [comment]
Just loading code into the nREPL works, **except** that lein-ring appears to be reloading code (and thus the original deployment, rather than changes) on every request regardless of how I set `auto-reload?`.  I'm trying to rule out if this because of something dumb / careless I'm doing; I'll create a separate issue if it turns out not to be.  Thank you!

**Comment by dkharlan** [comment]
For the record, this could also be caused by squiggly-clojure's reload behavior, so I'm not really sure if it makes sense for you guys to do anything about this yet.  I'll create a new issue if it does seem like a lein-ring problem, but at this point I'm betting on my setup.
