### ISSUE TITLE
Option :port not overwritten by environment 

### ISSUE THREAD

**Issue by nottmey** [weavejester/lein-ring#183]
I specified a port with `:port` for use in development, build an uberjar, and executed the jar. The port is not overwritten by `PORT` in the env.

```clojure
(defproject backend "0.0.1"
;; ...
  :plugins [[lein-ring "0.11.0"]]

  :ring {:handler backend.core/handler
         :port 8080})
```

```bash
$ lein ring uberjar
Compiling backend.core.main
Created ./target/backend-0.0.1.jar
Created ./target/backend-0.0.1-standalone.jar

$ java -jar target/backend-0.0.1-standalone.jar
Started server on port 8080 # ok

$ PORT=3030 java -jar target/backend-0.0.1-standalone.jar
Started server on port 8080 # not ok, but working without :port in project.clj

$ export PORT=3030
$ java -jar target/backend-0.0.1-standalone.jar
Started server on port 8080 # not ok, but working without :port in project.clj

$ echo $PORT
3030 # ...
```
I'm expecting this behaviour because of this sentence in the readme: `PORT` `SSLPORT` - "These will override any options specified in the `project.clj` file"

I'm trying this on
- OS X El Captain Version 10.11.6
- Leiningen 2.7.1 on Java 1.8.0_74 Java HotSpot(TM) 64-Bit Server VM

Any Idea why this is not working? Is this specific to my environment?

**Comment by nottmey** [comment]
After searching again I found a similar Issue with the same problem: #81 

The problem with `:port ~(or (Integer/parseInt (System/getenv "PORT")) 8000)` is that it only captures the `PORT` value at compile time. When executing the jar the `PORT` is ignored again.

**Comment by MichaelBlume** [comment]
hmm, ok, I guess it's actually not obvious when PORT *should* be paid attention to. @weavejester do you have opinions on this?

**Comment by weavejester** [comment]
I think it sounds sensible to have the `PORT` and `SSLPORT` vars checked at runtime when running an uberjar. Heroku in particular uses `PORT` at runtime to give the process the port number to listen on.

Does that sound logical?

**Comment by nottmey** [comment]
Many thanks for your response! 
For me it sounds logical: You specify your port with `:port` for having a different default value than `3000`. But you want to override that value any time later (when your uberjar is already build), by providing the port as `PORT` in the environment. (same goes for `SSLPORT`)

**Comment by MichaelBlume** [comment]
Aha, sorry, I misread, the problem isn't that the environment variable isn't read, it's that it doesn't take precedence over the project.clj options. I've pushed a pull request to ring-server which should change this

**Comment by joelash** [comment]
@MichaelBlume I just ran into this issue. I see the commit on `ring-server` but I don't see that it's been released since then. Is there some other way of getting this fix that I'm missing or do I just need to wait until `ring-server` is released again?

**Comment by MichaelBlume** [comment]
You could check out jitpack, which lets you depend on arbitrary git commits
but also I could release a lein-ring :)

**Comment by MichaelBlume** [comment]
Ok, looks like I actually can't fix this by releasing a lein-ring -- @weavejester could you release a ring-server at some point?

**Comment by weavejester** [comment]
Ah, I thought you had access. I've updated Clojars and added you to the ring-server group, @MichaelBlume.

**Comment by MichaelBlume** [comment]
Thanks =)

**Comment by MichaelBlume** [comment]
@joelash I'll get a lein-ring out eventually, but you can add a dependency on [ring-server "0.5.0"] right now and get this that way

**Comment by joelash** [comment]
Thanks
