### ISSUE TITLE
Auto reload seems brittle

### ISSUE THREAD

**Issue by 0atman** [weavejester/lein-ring#186]
When I make a syntax error in my clojure source, it doesn't auto-reload the files. That much is fair.
However, when I fix the syntax error, I have to restart the `lein ring server` task to get auto-reloading working again.

This is somewhat frustrating, as the nREPL DOES reload properly, I can see my updated code changes, but the HTTP interface is now stuck at whatever state it was before the original syntax error.

I had one of _those_ hours trying to find out why nothing I was doing to my code was changing what was reflected in the browser!

**Comment by 0atman** [comment]
Ah, my apologies, this only happens when I connect my IDE to the same nrepl that is running the server. I'll test more and if it actually affects me, I'll open another ticket

**Comment by Mitranim** [comment]
I found that auto-reload breaks on _manual_ reload from an nREPL connected to the same process. Brittle indeed. Any idea what's causing this?

**Comment by MichaelBlume** [comment]
Might be worth just not using auto-reload in that case and sticking with manual reload -- that's my usual development process.

That said, could you tell me how to reproduce?

**Comment by Mitranim** [comment]
I would much prefer to have both options available. Also, brittle tools are novice-unfriendly.

How to reproduce:

1. One terminal tab: `lein ring server-headless`
2. Other tab: `lein repl :connect`
3. Check that auto-reload works, even after errors
4. In the nREPL tab, run `(clojure.tools.namespace.repl/refresh)` or a similar function

**Comment by MichaelBlume** [comment]
Aha, yes, this is super annoying. The problem is that the server is bound to an old var and tools.namespace wants to create brand new namespaces with brand new vars on every reload. A hacky solution is to do something like this

```
(defn handler* [r]
  stuff goes here)

(defn handler [r]
  (let [resolved-handler (resolve `handler*)]
    (resolved-handler r)))
```

I believe there's an option that can be passed to ring-server that'll make it re-resolve on every request, so you don't have to do this, I'll go see what that is and if it's in release.

**Comment by Mitranim** [comment]
Nice, thanks for looking into this!

**Comment by MichaelBlume** [comment]
Ok, looks like if you use at least `0.12.1` of lein-ring (which I just released) and add `:re-resolve true` to your ring config, things should behave correctly -- can you let me know if I got that right?

**Comment by MichaelBlume** [comment]
(this was already in ring-server 0.5.0 but lein-ring didn't start bringing that in until 0.12.1. You can always depend on ring-server yourself if you want a version other than the one lein-ring brings in.)

**Comment by Mitranim** [comment]
Just checked; with `0.12.1` and `:re-resolve true` in `:ring` options, auto-reload keeps working after a manual refresh. Very nice! Big props for solving this so quickly. Maybe this should be the default in dev mode? Novices are likely to be tripped up by this.

**Comment by MichaelBlume** [comment]
Cool, thanks for reporting and checking =)

My inclination would be to have this as the default behavior, though I do
try to be pretty conservative about changing defaults.

I think this makes sense as long as we're in Dev profile

**Comment by Mitranim** [comment]
Noticed a minor change in behavior. Source reload now causes middleware to forget anti-forgery tokens, immediately invalidating forms. Minor annoyance. Any ideas? I could handle this on the application level by disabling anti-forgery in development, but there should be a better solution.

**Comment by MichaelBlume** [comment]
I think at that point you have a tools.namespace problem rather than a
lein-ring problem

**Comment by Mitranim** [comment]
Hmm but this happens on auto-refresh. Haven't even touched manual refresh.

**Comment by Mitranim** [comment]
Nevermind, figured out the problem: my session store was recreated on each refresh; solved by using `defonce`.

**Comment by MichaelBlume** [comment]
Aha, that makes sense, thanks for the update =)
