### ISSUE TITLE
ensure-handler-set! incorrectly calls System/exit

### ISSUE THREAD

**Issue by cursive-ide** [weavejester/lein-ring#196]
`leiningen.ring.util/ensure-handler-set!` checks that the `:handler` configuration is present in the project map, and calls `(System/exit 1)` if it is not. `System/exit` should never be called from within the lein process, including in plugin code. `leiningen.core.main/exit` should be called instead, which allows tools to rebind `*exit-process?*` to determine whether the process should actually quit or not.

In the case of Cursive, Cursive calls lein in several steps, some of which are performed in-process for performance. This bug means that a simple misconfiguration in the run configuration used to call lein will result in the entire IDE being shut down with no useful message displayed to the user.

**Comment by MichaelBlume** [comment]
Note, `leiningen.core.main/exit` has been present in leiningen since version 2.1.0, which was released in March 2013. I'm gonna make an executive decision and assume lein-ring users are using at least 2.1.0.

**Comment by MichaelBlume** [comment]
Done, fixed in `0.12.2`

**Comment by MichaelBlume** [comment]
Thanks =)

**Comment by cursive-ide** [comment]
@MichaelBlume Thanks for the quick response!
