### ISSUE TITLE
Dependency `unify` broken with Clojure 1.10

### ISSUE THREAD

**Issue by cch1** [weavejester/lein-ring#203]
lein-ring 0.12.4 
leinjacker 0.4.2
org.clojure/core.contracts 0.0.1
org.clojure/core.unify 0.5.3

This version of unify has a documented bug with clojure Spec: https://github.com/clojure/core.unify/commit/a5f60d74e1df61291535be43dab7bd2f2eaceb32

The result of this bug in my environment (leiningen 2.9.0 -> clojure 1.10.0 !!!!) is that lein-ring can't start.

**Comment by camsaul** [comment]
Clojure 1.10 isn't the issue. It's Leiningen 2.9.0 + any version of Clojure

**Comment by weavejester** [comment]
Leiningen 2.9.0 uses Clojure 1.10.0 internally, I believe, which causes the issue. Updating the `core.unify` dependency to 0.5.7 should solve the issue. PRs are welcome.

**Comment by camsaul** [comment]
Until a new version of `lein-ring` is out you override the `core.unify` dep e.g.

```clj
:plugins 
[[org.clojure/core.unify "0.5.7"]
 [lein-ring "0.12.4" :exclusions [org.clojure/core.unify]]]
```

Fixes it for me.

**Comment by camsaul** [comment]
@weavejester already working on it

**Comment by cch1** [comment]
Didn't realize it was a problem with older versions of Clojure as well -I thought spec had to be dragged in somehow.
