### ISSUE TITLE
uberwar task fails with latest leiningen versions

### ISSUE THREAD

**Issue by WorldsEndless** [weavejester/lein-ring#208]
Error is described and work around (downgrading leiningen) mentioned here: 

https://stackoverflow.com/questions/54948986/i-have-an-error-in-clojure-and-leiningen-command

It appears to be malformed code in a dependency.

**Comment by weavejester** [comment]
Are you using the latest version of Lein-Ring? The issue you describe seems similar to #203.

**Comment by WorldsEndless** [comment]
whoa... well, that fixed it, and I feel dumb. I ran `lein ancient` multiple times and it didn't see that version. Maybe Ancient doesn't check plugins. Thanks!
