### ISSUE TITLE
SslContextFactory$Server not found

### ISSUE THREAD

**Issue by t-matsudate** [weavejester/lein-ring#210]
Hi, @weavejester !

First, thank you for giving good tools and libraries!

When I tried to run the `lein ring server-headless`, I encountered following errors:

```
Syntax error (ClassNotFoundException) compiling at (ring/adapter/jetty.clj:1:1).
org.eclipse.jetty.util.ssl.SslContextFactory$Server
```

And my envirionments are following:

* JDK version: 12
* Clojure version: 1.10.1
* Ring version: 1.8.0
* lein-ring version: 0.12.5

Jetty version is the same as what Ring will depend on.
However this class is contained in also this version's Jetty.
Would you have some knowledge of this cause?

**Comment by weavejester** [comment]
Lein-Ring doesn't yet include the latest Ring adapter. Until it's updated, you'll need to add the Ring adapter dependency yourself:

    [ring/ring-jetty-adapter "1.8.0"]

**Comment by t-matsudate** [comment]
Oh!
This problem solved sure by trying your idea.
Therefore I'll close this issue.

Thank you for giving your idea and your precious time! :)
