### ISSUE TITLE
:listener-class 

### ISSUE THREAD

**Issue by ouvanous** [weavejester/lein-ring#212]
Hi, 
I am trying to nit a crux db node with the :init parameter. 
This works perfectly with a jar but once i try to use it as a war on tomcat. Tomcat is freezing and become unusable. 
The init function is called and create the db. But tomcat don't rn correctly anymore. 
my ring conf is something like : 
```
:ring {;:port 9999
                   :handler app.core/app
                   :init app.core/start-app!
                   :destroy app.core/stop-app!
                   :servlet-name "ehdsicts2_servlet"
                   :servlet-class "ehdsicts2_servlet"
                   :resources-war-path "WEB-INF/classes/"
                   :uberwar-name "ehdsicts2.war"}
```
and the init and destroy functions are : 
```
(defonce node (atom nil)); (start-node "crux-store"))

(defn start-node [storage-dir]
  (reset! node
          (crux/start-node {:crux.node/topology '[crux.standalone/topology
                                                  crux.kv.rocksdb/kv-store]
                                         :crux.standalone/event-log-dir "/Users/ouvanous/ehdsi-cts/crux-store/eventlog-1"
                                        :crux.standalone/event-log-kv-store 'crux.kv.rocksdb/kv
                               :crux.kv/db-dir (str "/Users/ouvanous/ehdsi-cts/crux-store/db")}))
  nil)

(defn stop-node
  []
  (.close @node))

```

I can't find anything in the logs and wonder if it is related to the :listener-class?
The docs are saying : 
:listener-class - Class used for servlet init/destroy functions. Called listener because underneath it uses a ServletContextListener.

But i understand what i should do with that? 

Many thanks for any tips ? 
Best regards, 
Samuel

**Comment by weavejester** [comment]
You may want to check whether or not Crux is blocking the current thread, and whether or not Tomcat allows background threads, or what its permission model is like for servlets.

**Comment by ouvanous** [comment]
Many thanks @weavejester 
I don't know how to do that but i'll search 
Thanks again
