### ISSUE TITLE
uberjar fails to build when log4j.properties references dependency

### ISSUE THREAD

**Issue by cch1** [weavejester/lein-ring#40]
(lein ring 0.7.0, Clojure 1.2.1, log4j 1.2.16)

My resources/log4j.properties file references an appender that available in a dependency.

log4j.properties:
log4.rootLogger=INFO,A1, LOGGLY
log4j.appender.LOGGLY=com.roomkey.cloggly.LogglyAppender
...

And in project.clj
{...
  :dependencies [...
                           [com.roomkey/cloggly "1.2"]
                        ...]

...}

Removing LOGGLY from the first line of log4j.properties allows uberjar to work.  WIth it in there, uberjar never finishes.

With LOGGLY in place, I can run "lein ring server" and all the other typical leiningen commands without issue.  But building an uberjar fails.

Regards,
Chris

**Comment by MichaelBlume** [comment]
Hey, you're using Loggly, that's awesome, I used to work there for a while, they're good people =)

So I don't see com.roomkey/cloggly available for download anywhere, but I threw together a project with https://github.com/ryantenney/log4j-redis-appender and used that as a log4j appender and everything seemed basically fine.

I'm gonna close this for now, but feel free to reopen if you think there's still a problem and want to help me reproduce it.
