### ISSUE TITLE
Always AOT-compiles my whole project

### ISSUE THREAD

**Issue by amalloy** [weavejester/lein-ring#52]
When I do `lein ring server`, I see "Compiling myapp.main" and then a very long pause while my entire app and all libraries are AOTed. There is no `:gen-class` in this namespace, and no need for lein-ring to create an uberwar or anything, so I can't see why anything needs to be AOTed. The slowness is a huge problem, of course, and additionally it leaves around tons of old classfiles, so that if I check out a different git branch with different dependencies, I get conflicts when the old classfiles are used against the new dependencies (at least I think that's what's going on). I have to `lein clean` and then AOT the whole thing again, wasting many minutes.

My project.clj contains:

      :ring {:handler myapp.main/handler
             :port 9255
             :open-browser? false
             :init myapp.main/init
             :destroy myapp.main/destroy
             :web-xml "web.xml"}

Is this a known bug in lein-ring? A feature that for some reason I should learn to love? Something that I can easily turn off?

**Comment by MichaelBlume** [comment]
Declaring this closed by #134
