### ISSUE TITLE
'lein ring uberjar' ignores :nrepl option

### ISSUE THREAD

**Issue by laczoka** [weavejester/lein-ring#79]
It seems lein ring uberjar doesn't add the nrepl server if configured

**Comment by MichaelBlume** [comment]
Yeah, I think this is a documentation issue, I'll try to push something up soon.

I think we are less likely to unpleasantly surprise users by sticking with the current behavior, with the understanding that you can add a call to clojure.tools.nrepl.server/start-server to your :init function if you want to debug your staging/production instances.
