### ISSUE TITLE
How to send exceptions to nrepl in Emacs?

### ISSUE THREAD

**Issue by tvaughan** [weavejester/lein-ring#86]
In my project.clj I have:

```
:ring {:handler myproject.handler/app :nrepl {:start? true}}
```

With this I can run `lein ring server` and attach to the nrepl from Emacs with `M-x nrepl`. FWIW, In my ~/.emacs.d/init.el I also have this:

```
(require 'nrepl)
(add-hook 'nrepl-interaction-mode-hook
          (lambda ()
            (require 'nrepl-ritz)))
```

But I've noticed that any exceptions thrown by my compojure app are shown in the command-line window where I ran `lein ring server`, not in the nrepl buffer in Emacs. I'd like to be able to inspect the exceptions and step through the stack trace with ritz in Emacs.

I'm really not sure what's needed. I suspect that `lein ring server` needs to be modified to start a ritz server instead of an nrepl server, right? Or should I tackle this another way? Like start the ring server in the nrepl in Emacs?

Thank you.

**Comment by MichaelBlume** [comment]
This is kind of a work-around but you might have better luck starting your web server from within your REPL using run-jetty.

**Comment by carrete** [comment]
> Or should I tackle this another way? Like start the ring server in the nrepl in Emacs?

This is the answer, as @MichaelBlume says above too.

PS - I lost my access to the @tvaughan account. This issue can be closed (I no longer have the option to do so). Happy 10 year anniversary! 🎉
