### ISSUE TITLE
uberwar doesn't resolve functions in :manifest

### ISSUE THREAD

**Issue by hanjos** [weavejester/lein-ring#91]
This is somewhat related to #89: Leiningen supports [functions in the manifest](https://github.com/technomancy/leiningen/blob/stable/sample.project.clj#L349). So one possible solution to #89 would be generating manually a manifest, which holds the version. The manifest would use some functions to generate the entries, avoiding duplication:

```
:manifest {"Name" ~#(str (clojure.string/replace (:group %) "." "/")
                            "/" (:name %) "/")
             "Package" ~#(str (:group %) "." (:name %))
             "Specification-Title" ~#(:name %)
             "Specification-Version" ~#(:version %)})
```

with `lein uberjar`, the resulting MANIFEST.MF is:

```
Manifest-Version: 1.0
Build-Jdk: 1.6.0_45
Built-By: me
Name: my/company/project/
Package: my.company.project
Created-By: Leiningen 2.3.2
Specification-Title: project
Specification-Version: 0.3.0-SNAPSHOT
```

with `lein ring uberwar`, the resulting MANIFEST.MF is:

```
Manifest-Version: 1.0
Built-By: me
Name: leiningen.core.project$eval11$fn__12@346df9bc
Package: leiningen.core.project$eval11$fn__14@27261218
Created-By: Leiningen Ring Plugin
Specification-Title: leiningen.core.project$eval11$fn__16@2c154024
Specification-Version: leiningen.core.project$eval11$fn__18@5eb8f6d
```

**Comment by MichaelBlume** [comment]
Aha, well this is a problem. I wonder if we can sort this by just calling leiningen.jar/make-manifest instead of rolling our own? I'll try to look into this more soon. Thanks!
