### ISSUE TITLE
Upgrade to support future leiningen versions

### ISSUE THREAD

**Issue by laczoka** [weavejester/lein-ring#94]
With leiningen 2.3.3, running

lein ring uberjar

the following warning appears:

Warning: specified :main without including it in :aot. 
Implicit AOT of :main will be removed in Leiningen 3.0.0. 
If you only need AOT for your uberjar, consider adding :aot :all into your
:uberjar profile instead.

**Comment by MichaelBlume** [comment]
Fixed =)

**Comment by MichaelBlume** [comment]
(fixed in master, not yet in release)
